spring:
  datasource:
    platform: ${DATABASE_PLATFORM}
    driverClassName: ${DATABASE_DRIVER}
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  application:
    name: storage-service

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8000

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

logstash:
  enabled: true
  host: ${LOGSTASH_HOST:localhost}
  port: ${LOGSTASH_PORT:5000}
  queue-size: 512

keycloak:
  realm: MicroservicesRealm
  auth-server-url: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8180}/auth
  resource: storage-service
  use-resource-role-mappings: true
  bearer-only: true